### ISSUE TITLE
'Unknown error' when connecting third-party application to chacon's cloud

### ISSUE THREAD

**Issue by raisra** [cnico/dio-chacon-wifi-api#1]
I can't add my Chacon plug to Google Home, Alexa, or IFTTT anymore.

When I try to add my device, it asks me to connect to the Chacon cloud, which I successfully do. However, when I click the authorize button to allow the use of my plug, I get an "unknown error"  as shown below.

![Screenshot_2024-08-16-05-22-39-126_com android chrome](https://github.com/user-attachments/assets/88c4a889-fae6-4da5-b0c0-2c00c7e0a856)

**Comment by raisra** [comment]
![Screenshot_2024-08-16-05-22-39-126_com android chrome](https://github.com/user-attachments/assets/b867f299-d1f5-4046-aeac-237f03b8e312)

**Comment by cnico** [comment]
Hi @raisra,
Can you tell more about your context of usage of this dio chacon api ?
Is it directly in a python program, via homeassistant or other ?
What are the actions before the error ? On which browser or mobile app are you, what url are you going to before the error, etc ?
In your usage of the api, what logs do you have when you use it with debug activated ?

Note: this api is not related to ifttt or other integrations. It simply uses chacon's cloud Api as the mobile app does so there is no obvious reason why using this Api could cause the error you get.

**Comment by cnico** [comment]
No news so closing it.
